import './globals.css'
import { Inter } from 'next/font/google'

import { ReactNode } from "react";

interface Props {
    children: ReactNode;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
